### ISSUE TITLE
Uncompleteable Quest

### ISSUE THREAD

**Issue by Rublebuble** [fullphaser/Tame-The-World#5]
Hi
In Immersed in Engineering.

Quest #420: cant compleate the second part Fiberous Fun.
Is it a crafting task? Because you get it as a drop.

I sell Coke Ovens: Is it your intention to craft 54 Blocks? also 2 Ovens?

**Comment by Alnarra** [comment]
Both I believe are fixed in the Nightly Builds

**Comment by Rublebuble** [comment]
Ok
but i think i found another one 
Byproduct: to craft 8 treated wood, but you need to craft 64

**Comment by Alnarra** [comment]
Should also be corrected. Here's the full current changelog for 0.1.1.  as of this morning 

Version 0.1.11 
Mods Added 
- Cooking for Blockheads 
- FTB Utilities 
- FTB Lib 
- Not Enough Resources 
- Bakcpacks mod Added

Mods Removed 
- Aroma Core
- Aroma Backup 

Mods Updated
- Botania (Was Version r1.8 247 - now r 1.8 248 )
- Hardcore ender Expansion (was 1.8.4 now 1.8.5) 
- Automagy (Was 0.27 now 0.27.1 ) 
- Forbidden Magic (Was 0.572 now 0.573 ) 
- Immersive Engineering ( Was 0.651 now 0.70 ) 
- Growthcraft Community Edition ( Was 0.2.3.1 now 0.2.4.0 ) 
- Roguelike Dungeons (was 1.3.6.3 now 1.4.4) 
- Ruins
- Storage Drawers ( Was 1.7.5 now 1.7.7 ) 
- Spiace of Life (Was 1.3.0 now 1.3.1 ) 

Config Updates 
- Removed Apples from Default spawn for FTB util 
- Changed Default MOTD 
- Turned on the Creative Thaumonomicon 
- Reduced Taint Spread a bit 

Script 
- Created fruitSap.zs to help with Cherry Quest 

Quest 
- Created two new Chapters for Rotarycraft and Thaumcraft 
- Chapter 1 - How to use the Book - Added a reward of wood 
- Chapter 1 - Added quest for Backpacks 
- Agriculture - Added Quest to accomodate the addition of Cooking for Blockheads 
- Agriculture - Changed Falling Far From the Tree to Ore Dictionary Detection 
- Chapter 2 - You're a Wizard Harry - Changed Quest from Crafting to Detection 
- Chapter 2 - You're a Wizard Harry - Nuggets - Decreased number of times to craft to 2 (Was 10) 
- Chapter 2 - Added quest for Spectral Key 
- Chapter 2 - Corrected Botania petal Apothocary Quest to now be Detection based 
- Immersed in Engineering - Quest 420 - Changed to Detection for Hemp  
- Immersed in Engiineering - Industrial Expansion - Updated for 0.70 Update 
- Immersed in Engineering - Winding up - Low Voltate Fun - Changed LV Capacitor to NPT Independent Detection 
- Immersed in Engineering - Added quest for "Improved Blast Furance
- Immersed in Engineering - Steeling the Show - Decreased number of times to Craft to 14 (Was 27) 
- Immersed in Engineering - I sell Coke Ovens - Decreased number of times to craft to 14 (Was 27) 
- Immersed in Engineering - Byproduct - Decreased number of times to craft to 1 (Was 8) 
- Botaniacal Relevance - Weaving a Destiny - Fixed the Cowl (I think)

**Comment by Alnarra** [comment]
This should now be corrected

**Comment by vagaprime** [comment]
Playing on 0.1.11 of the pack. the quest for the iron capped wand will not detect the wand. The grit quest in the IE chain can not be completed cause the hammer can not be used to crush the ores. I have even set the force hammer crushing option to true in the config and the grit still does not have a crafting recipe with the hammer.

**Comment by Alnarra** [comment]
If you fill the wand does that correct it? 

Also the Grit is something I'm aware of, I've opened a case with BlueSunrize over at Immersive Engineering to try and figure it out

**Comment by vagaprime** [comment]
will need to start a new world to find out if a fully charged wand will work. When you set the wand did you have one that you crafted or did you set from the books search? I have found that with some mods  selecting items from the search option in the book tends to cause problems.

**Comment by Alnarra** [comment]
Yeah I'm going to go ahead and set it to a crafted wand in 0.1.12 I'm just curious if it can even be gotten past in 0.1.11 considering that a fairly large component of this last update was the Thaumcraft chapter.
